version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  btc-app-image:
    build: ./
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
