version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5

  btc-app-image:
    build: ./mainApp
    restart: always
    ports:
      - 8080:8080

  customer:
    build: ./customers
    image: customers
    restart: always
    ports:
      - 8081:8081


  mysql:
    image: mysql:8
    restart: always
    ports:
      - "8092:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=saga
      - MYSQL_USER=saga
      - MYSQL_PASSWORD=saga
    networks:
      - backend

  dtm:
    image: yedf/dtm
    restart: always
    ports:
      - "36790:36790" # grpc
      - "36789:36789" # ui
    networks:
      - backend

networks:
  backend:
    driver: bridge